
services:
  notification-worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ../db/superior-agents.db:/app/notification/db/superior-agents.db